### ISSUE TITLE
Jetbrains/IDE key shortcuts

### ISSUE THREAD

**Issue by iangregsondev** [warpdotdev/keysets#2]
I currently use a lot of JetBrains IDEs and even have my VSCode key bindings set to the same as Jetbrains.

Would be nice to have some key bindings for Warp using the same keys as Jetbrains, where it makes sense of course.

i.e. Multi Cursor, Open pallete, etc etc etc.

Cheers.

**Comment by elviskahoro** [comment]
@iangregsondev This is a great idea. I can set this up eventually.

**Comment by elviskahoro** [comment]
Gonna move these issues to the Warp repo:
https://github.com/warpdotdev/Warp/issues/2810
