### ISSUE TITLE
Overwrite `cmd+k` shortcut

### ISSUE THREAD

**Issue by HenryC-3** [warpdotdev/keysets#6]
Hi.  Warp assigns `cmd+k` to `clear blocks` by default, which is not available in `keybindings.yaml`.

Is `cmd+k` overwriteable?

<img width="996" alt="image" src="https://user-images.githubusercontent.com/41246463/203536620-f32861d7-8765-44c4-a0f7-7f8e3c91c74e.png">

**Comment by elviskahoro** [comment]
I reached out to the team and we're going to create a ticket for this as it's a bug!

**Comment by elviskahoro** [comment]
@HenryC-3 gonna close this and open a new issue in the Warp repo.
