### ISSUE TITLE
More flexibility with custom keybindings

### ISSUE THREAD

**Issue by DIvkov575** [warpdotdev/keysets#7]
previously I had cmd+/ bound to a set of character codes which in turn commented lines in vim. As far as I know, Warp does not provide any way to set custom characters as keybindings. Additionally, I have not found a way to override the current cmd+/ opening the keyboard shortcuts panel key bind. Because of this I am would be unable to preform necessary tasks from my old workflow.
 I love the idea of warp, but this would be the decision-making feature for me.

**Comment by elviskahoro** [comment]
Moving this to Warp repo:
https://github.com/warpdotdev/Warp/issues/2811
